# Generated by Django 4.0 on 2022-04-04 01:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('food', 'food'), ('accompaniments', 'accompaniments'), ('beverages', 'beverages'), ('Veggies', 'Veggies')], max_length=100)),
                ('available', models.CharField(choices=[('Unavailable', 'unavailable'), ('Available', 'available')], max_length=50)),
                ('size', models.CharField(blank=True, choices=[('Full', 'full'), (0.25, 'quarter'), (0.5, 'half')], max_length=20)),
                ('slug', models.SlugField()),
                ('food_pic', models.ImageField(blank=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=50)),
                ('open_status', models.CharField(choices=[('OP', 'open'), ('CL', 'closed')], max_length=10)),
                ('days_open', models.CharField(choices=[('Everyday', 'everyday'), ('Weekdays', 'weekdays'), ('Everyday excluding Sunday', 'everyday excluding sunday'), ('Everyday plus holidays', 'everyday plus holidays')], max_length=100)),
                ('fish_type', models.CharField(choices=[('Fresh, Ungutted, Chilled', 'Fresh, Ungutted, Chilled'), ('Fresh, Ungutted, Frozen', 'Fresh, Ungutted, Frozen'), ('Fresh, Gutted, Chilled', 'Fresh, Gutted, Chilled'), ('Fresh, Gutted, Frozen', 'Fresh, Gutted, Frozen'), ('Processed, Fillet, Chilled', 'Processed, Fillet, Chilled'), ('Processed, Fillet, Frozen', 'Processed, Fillet, Frozen'), ('Processed, Sundried', 'Processed, Sundried'), ('Processed, Smoked', 'Processed, Smoked'), ('Processed, Fried', 'Processed, Fried')], max_length=100)),
                ('franchise_pic', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('UP', 'Unprocessed'), ('P', 'Processed')], max_length=5)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'Processed'), ('D', 'danger')], max_length=2)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('item_pic', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Mongers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=80)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('monger_pic', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.billingaddress')),
                ('items', models.ManyToManyField(to='store.RestaurantOrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=100)),
                ('coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('open_status', models.CharField(choices=[('OP', 'open'), ('CL', 'closed')], max_length=10)),
                ('days_open', models.CharField(choices=[('Everyday', 'everyday'), ('Weekdays', 'weekdays'), ('Everyday excluding Sunday', 'everyday excluding sunday'), ('Everyday plus holidays', 'everyday plus holidays')], max_length=100)),
                ('restaurant_pic', models.ImageField(upload_to=None)),
                ('food_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('reserveDate', models.DateField()),
                ('phoneNumber', models.CharField(max_length=100)),
                ('reserveTime', models.DateTimeField()),
                ('familySize', models.IntegerField()),
                ('reserveOrder', models.TextField()),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.billingaddress')),
                ('items', models.ManyToManyField(to='store.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
