# Generated by Django 4.0 on 2022-03-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_payment_delete_myobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('food', 'food'), ('accompaniments', 'accompaniments'), ('beverages', 'beverages'), ('Veggies', 'Veggies')], max_length=100),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='fish_type',
            field=models.CharField(choices=[('Fresh, Ungutted, Chilled', 'Fresh, Ungutted, Chilled'), ('Fresh, Ungutted, Frozen', 'Fresh, Ungutted, Frozen'), ('Fresh, Gutted, Chilled', 'Fresh, Gutted, Chilled'), ('Fresh, Gutted, Frozen', 'Fresh, Gutted, Frozen'), ('Processed, Fillet, Chilled', 'Processed, Fillet, Chilled'), ('Processed, Fillet, Frozen', 'Processed, Fillet, Frozen'), ('Processed, Sundried', 'Processed, Sundried'), ('Processed, Smoked', 'Processed, Smoked'), ('Processed, Fried', 'Processed, Fried')], max_length=100),
        ),
    ]
