# Generated by Django 4.0 on 2022-03-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_fooditem_food_pic_franchise_franchise_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_pic',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='size',
            field=models.CharField(blank=True, choices=[('Full', 'full'), (0.25, 'quarter'), (0.5, 'half')], max_length=20),
        ),
    ]
