# Generated by Django 4.0 on 2022-03-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0005_alter_fooditem_food_pic_alter_fooditem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserveDate', models.DateField()),
                ('phoneNumber', models.CharField(max_length=100)),
                ('reserveTime', models.DateTimeField()),
                ('familySize', models.IntegerField()),
                ('reserveOrder', models.TextField()),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
