from django.urls import path,include
from store.views import (CheckoutView, FoodDetailView, FoodOrderSummaryView, ItemDetailView, MongerView,
 RestaurantView,
  VendorView,
HomeView,
OrderSummaryView,
add_to_cart, food_add_to_cart, food_remove_from_cart, getAccessToken,
remove_from_cart, remove_single_fooditem_from_cart,
remove_single_from_cart,
about_page,
TestView,
FoodItemView,
PaymentView, stk_push_callback, test_lipa)

app_name='store'
urlpatterns=[
    path('',HomeView.as_view(),name='home'),
    path('products/<slug>/',ItemDetailView.as_view(),name='products'),
    path('food-products/<slug>/',FoodDetailView.as_view(),name='food-products'),
    path('checkout',CheckoutView.as_view(),name='checkout'),
    path('order-summary',OrderSummaryView.as_view(),name='order-summary'),
    path('food-order-summary',FoodOrderSummaryView.as_view(),name='food-order-summary'),
    path('about',about_page,name='about'),
    path('vendor',VendorView.as_view(),name='vendor'),
    path('mongers',MongerView.as_view(),name='mongers'),
    path('test',TestView.as_view(),name='test'),
    path('restaurants/',RestaurantView.as_view(),name='restaurants'),
    path('food_items',FoodItemView.as_view(),name='food_items'),
    path('add-to-cart/<slug>/',add_to_cart,name='add-to-cart'),
    path('food-add-to-cart/<slug>/',food_add_to_cart,name='food-add-to-cart'),
    path('remove-from-cart/<slug>/',remove_from_cart,name='remove-from-cart'),
    path('remove-food-from-cart/<slug>/',food_remove_from_cart,name='remove-food-from-cart'),
    path('remove-fooditem-from-cart/<slug>/',remove_single_fooditem_from_cart,name='remove-fooditem-from-cart'),
    path('remove-item-from-cart/<slug>/',remove_single_from_cart,name='remove-single-item-from-cart'),
    path('access/token',getAccessToken,name='get-mpesa-access-token'),
    # path('api/v1/online/lipa',lipa_na_mpesa_online,name='lipa-na-mpesa'),
    path('payment/',PaymentView.as_view(),name='payment'),
    path('lipastk',test_lipa,name='lipastk'),
    path('stkpush',stk_push_callback,name='mpesa_stk_push_callback'),
]